---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: demo-deployment
        namespace: demo
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: java
        template:
                metadata:
                        name: Demo-pod
                        labels:
                                app: java
                spec:
                        nodeSelector:
                           name: worker-1
                        containers:
                                - name: demo-conatiner
                                  image: joe2061/gitimage:tagname
                                  ports:
                                  - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
        name: demo-service
        namespace: demo
spec:
        type: NodePort
        ports:
                - port: 80
                  targetPort: 8080
        selector:
                app: java
